### ISSUE TITLE
api_cred resource update required

### ISSUE THREAD

**Issue by kreynoldsf5** [volterraedge/terraform-provider-volterra#71]
The api_cred resource needs to be updated after the 7/15 schema changes. 

The **/api/web/namespaces/system/api_credentials** endpoint now _requires_ a "expiration_days" parameter (with a value of _int_) as opposed to the "expirationTimestamp" parameter currently being passed.

Here is the current payload generated by the [api_cred](volterra/resource_volterra_api_credential.go) resource.

```json
{"namespace":"system","name":"demo-app-api-cred","spec":{"type":"KUBE_CONFIG","virtualK8sNamespace":"demo-app","virtualK8sName":"demo-app-vk8s"},"expirationTimestamp":"2021-07-26T15:17:10.181527914Z"}
```

Here is an example payload that the resource will need to create:

```json
{"namespace":"system","name":"demo-app-api-cred","spec":{"type":"KUBE_CONFIG","virtualK8sNamespace":"demo-app","virtualK8sName":"demo-app-vk8s"},"expiration_days":10}
```

This change will render this [function](https://github.com/volterraedge/terraform-provider-volterra/blob/main/volterra/resource_volterra_api_credential.go#:~:text=func%20parseExpirationTime) unnecessary.

_Please note that the provider is unable to create any type of api credential in its current state._

**Comment by kreynoldsf5** [comment]
see #72.

**Comment by madhukar32** [comment]
@kreynoldsf5: Thanks for the PR, I realized later that we need to pull the latest schema and few more things to adapt the new change. Created a new PR with those changes

**Comment by s-archer** [comment]
I also ran into this problem.  

The current version of the Terraform resource generates a curl which is passing parameter "expirationTimestamp", but the API requires "expiration_timestamp".

**Comment by madhukar32** [comment]
Created a new release v0.8.1
Its fixed in that, can you pls confirm

**Comment by s-archer** [comment]
Yes, it’s fixed!

Cheers,

***@***.***D3E6A8.FAEE45D0]<https://f5.com/>
Stephen Archer  |  Sr. Solution Engineer – Cloud & Automation
M +44 (0)7788 446 470
***@***.***D3E6A8.FAEE45D0]<https://twitter.com/F5Networks/>
***@***.***D3E6A8.FAEE45D0]<https://www.linkedin.com/companies/f5-networks>
***@***.***D3E6A8.FAEE45D0]<https://www.facebook.com/f5networksinc>
***@***.***D3E6A8.FAEE45D0]<https://www.youtube.com/f5networksinc>
***@***.***D3E6A8.FAEE45D0]<https://devcentral.f5.com/>

***@***.***D3E6A8.FAEE45D0]<https://www.certmetrics.com/f5certified/public/badge.aspx?i=6&t=c&d=2018-05-04&ci=F50000003932>[signature_2061336585]



From: Madhukar Nayakbomman ***@***.***>
Date: Friday, 23 July 2021 at 15:45
To: volterraedge/terraform-provider-volterra ***@***.***>
Cc: Stephen Archer <S.Archer@F5.com>, Comment ***@***.***>
Subject: Re: [volterraedge/terraform-provider-volterra] api_cred resource update required (#71)

EXTERNAL MAIL: ***@***.***

Created a new release v0.8.1
Its fixed in that, can you pls confirm
